### ISSUE TITLE
When posting from Twitter to Mastodon convert @xx in @xx@twitter.com

### ISSUE THREAD

**Issue by jrmgx** [halcy/MastodonToTwitter#36]
I think it could be a plus for mastodon user to see that the post come from twitter
so they don't look for the @xx on their instance and understand that it is from twitter
The idea is to add a conversion in twitter post changing every @xx in @xx@twitter.com

I don't know much python but if you are ok but don't have time to do it I can try a PR

Have a good day

**Comment by EntropiaFox** [comment]
Oh, I've started #38 already to handle this as part of a few other changes I've wanted to add, let's see if it gets accepted, though. Ideally, it should work the other way around too, but Twitter's tighter character limit makes it tougher to signal a given mention comes from Mastodon instead of Twitter.

**Comment by halcy** [comment]
Closed by PR.
