### ISSUE TITLE
Unmaintained

### ISSUE THREAD

**Issue by remram44** [halcy/MastodonToTwitter#54]
Last week @halcy (author) pushed [this commit](https://github.com/halcy/MastodonToTwitter/commit/ae9863e14392564b1a1294afdc4fdcd88e7852ea), stating that this script is now unmaintained, since he doesn't use it anymore.

Is anyone interested in taking this over?

There are some pressing issues such as:
* [boosts are not marked as retweets (#51)](https://github.com/halcy/MastodonToTwitter/issues/51)
* [retweets don't get forwarded at all (#29)](https://github.com/halcy/MastodonToTwitter/issues/29)
* [private toots probably shouldn't get forwarded (#34)](https://github.com/halcy/MastodonToTwitter/issues/34)

I see that @AmauryCarrade probably has done the most work on this script, adding
* [support for threads](https://github.com/AmauryCarrade/MastodonToTwitter/commit/2120a991a42f868e32d9321527e51ca734a81b62): toots/tweets that are replies to more of your own toots/tweets should keep that relationship when forwarded (need to keep a mapping of forwarded IDs for that)
* [support for content warnings](https://github.com/AmauryCarrade/MastodonToTwitter/commit/5e561b1e45f0b6aa799e042dbc9dae1f9b1f098c)

Do you want to take it over? Does anyone else?

I am going to use this script as I try to move to Mastodon more seriously, so I'll see if I can tackle some of the issues myself (but I don't have that much free time).

[edit: started [my own program](https://gitlab.com/remram44/microforwarder) so I probably won't be contributing here]

**Comment by halcy** [comment]
Let me know if / when you are happy with the state of yours, I'll put a link in the README

**Comment by goatrocks** [comment]
I use this currently, so I would be willing to take over. I'll take a stab at a couple of the open issues before I commit to be sure :smile_cat:

**Comment by halcy** [comment]
Good to hear. If you decide you do want to work on it, just comment again, and I can transfer the repository to your account.

**Comment by AmauryCarrade** [comment]
Hi! I can also take this, or with @meggle. I only have to finalize my PRs (was paused for a long time for personal reasons), the ones mentioned by this issue's author. The RT bug also annoy me so if no one fix it I'll probably look into that. Well, except if all user migrate to @remram44's program :) .

**Comment by remram44** [comment]
FYI: I'm no longer working actively on my program because of this: https://crossposter.masto.donte.com.br/ (Ruby, [sources](https://github.com/renatolond/mastodon-twitter-poster))

I might still finish it sometime 😶

-----

<table>
<tr><th>Name</th><th>URL</th><th>Source</th><th>Language</th></tr>
<tr><td>mastodon-twitter-poster</td><td><a href="https://crossposter.masto.donte.com.br/">https://crossposter.masto.donte.com.br/</a></td><td><a href="https://github.com/renatolond/mastodon-twitter-poster">GitHub</a></td><td>Ruby</td></tr>
<tr><td>Moa</td><td><a href="https://moa.party/">https://moa.party/</a></td><td><a href="https://github.com/foozmeat/moa">GitHub</a></td><td>Python</td></tr>
</table>

**Comment by foozmeat** [comment]
I'll also  throw in a plug for my cross-posting service

https://moa.party

**Comment by AmauryCarrade** [comment]
[I worked on this script on my fork](https://github.com/AmauryCarrade/MastodonToTwitter/), bringing 280-characters support, retweets & boosts support, and real-time crossposting (using streaming APIs of both Twitter and Mastodon instead of regular pulling)—if some are interested. I also refactored the code a little bit (ok, quite a lot).

It's still in beta; I'm testing it on my own Twitter/Mastodon accounts @AmauryPi[@unixcorn.xyz] (including high usage yesterday) without significant problems for now. On my TODO list:

- better hashtag support for split tweets;
- better boosts support from Mastodon (the streaming API does not stream boosts in all cases, so I'll have to find another way);
- better long-term stability (sometimes, but that was also the case before with halcy's version, Twitter or Mastodon closes the connection without notice);
- options regarding to private toots forwarding (#34).

**Comment by halcy** [comment]
I would really like to add a redirect to that - but I don't know if I can do it without transferring the repo. Should I try to do that?

**Comment by AmauryCarrade** [comment]
If you are OK with the idea of transferring the repo, [it will indeed redirect](https://help.github.com/articles/about-repository-transfers/#whats-transferred-with-a-repository) (and if it's the case, you'll be added as a contributor with _push access_, and clear attribution in the README, of course).

In this case, I think the easiest way to do so is the following.

1. I open a PR to bring my changes in this repo;
2. You merge it; I delete my fork;
3. You transfer the repository.

The pull request, merge and fork deletion are required because you cannot transfer a repository to an account with a repository of the same name or a fork of the same network—and I have both, currently.

If you don't want to transfer your rights, and that would be completely understandable, there's no way to redirect, but you can put a link in the README.

**Comment by halcy** [comment]
Sorry for the very late reply. Sounds good to me - feel free to submit that PR!
